### ISSUE TITLE
`id` fields on data models are not JSON Schema-compliant

### ISSUE THREAD

**Issue by jacoblurye** [CIMAC-CIDC/cidc-schemas#10]
Right now, our `id` fields just contain unique identifiers, but to comply with the JSON Schema spec, the `id` field on all JSON data models should be a URI referring to where that schema can be downloaded.

See: https://json-schema.org/understanding-json-schema/structuring.html#id

Either we could make these `id`'s point at the GitHub raw content URIs where the schemas are hosted, or we could rename the `id` field to something that isn't a JSON Schema keyword (e.g., `name`).

**Comment by jim-bo** [comment]
Good point. @jacoblurye can you modify pbmc schemas and manifest to comply with the requirements.
