### ISSUE TITLE
module dependencies are not in the setup.py requirements

### ISSUE THREAD

**Issue by jason-weirather** [CIMAC-CIDC/cidc-schemas#26]
Errors running `cidc_schemas -h`

```
ModuleNotFoundError: No module named 'yaml'
ModuleNotFoundError: No module named 'dateparser'
```

### Fixed with
* `pip install PyYAM`
* `pip install dateparser`

Maybe we can add these to the setup.py

**Comment by jason-weirather** [comment]
Related, theres some minimum version requirement on jsonschema since it has the `draft7validator` being used.

**Comment by jason-weirather** [comment]
`xlsxwriter` is another missing requirement

**Comment by jason-weirather** [comment]
`pytest` may be good to have in the recommended modules

**Comment by jacoblurye** [comment]
https://github.com/CIMAC-CIDC/cidc-schemas/pull/118
