### ISSUE TITLE
Validator breaks if certain fields are empty.

### ISSUE THREAD

**Issue by priti88** [CIMAC-CIDC/cidc-schemas#28]
olink: Data, RUN_DATE:  could not convert "None" to date
olink: Data, RUN_TIME:  could not convert "None" to time

How we we specify fields which can have Null value?

**Comment by mducar** [comment]
I'm having the same issue with RNAseq.  The reverse fastq file is optional.

**Comment by jacoblurye** [comment]
Good point -- there was no support for non-required fields, but I added it in #31.

Now, if you add a list of "required" fields in your template schema, you'll only getting validation errors for missing values on those required fields.
