### ISSUE TITLE
Does validate_template only validate first sheet?

### ISSUE THREAD

**Issue by priti88** [CIMAC-CIDC/cidc-schemas#57]
WARNING:root:Found multiple worksheets in template_examples/cytof_template.xlsx - only parsing Data Acquisition
template_examples/cytof_template.xlsx is valid with respect to schemas/templates/metadata/cytof_template.json

**Comment by jacoblurye** [comment]
You're probably running an outdated version of the CLI locally. To update, just re-run `python setup.py install`. 

Or, to ensure you're always up-to-date, you can run the CLI with `python -m cidc_schemas.cli [args]`.
