### ISSUE TITLE
tcr_fastq and tcr_adaptive is_artifact value is unclear

### ISSUE THREAD

**Issue by crouchcd** [CIMAC-CIDC/cidc-schemas#575]
https://github.com/CIMAC-CIDC/cidc-schemas/blob/a041af26493861a60f10126c0fd7203ece8bdae0/cidc_schemas/schemas/templates/assays/tcr_fastq_template.json#L54-L59

TCR is the only exception to the rule of 0, 1, or "multi" for "is_artifact" values.

If I change to `"is_artifact": 1`, pytest fails. I had to change the value of the merge_pointer to: `/r1/0`, but I'm not sure if that is correct (even though the tests pass).

**Comment by scvannost** [comment]
so `"/records/0/files/replicates/-"` we're working in here is defined [in the tcr_assay schema](https://github.com/CIMAC-CIDC/cidc-schemas/blob/a041af26493861a60f10126c0fd7203ece8bdae0/cidc_schemas/schemas/assays/tcr_assay.json#L82) and eg `r2` points to [reads_with_index](https://github.com/CIMAC-CIDC/cidc-schemas/blob/a041af26493861a60f10126c0fd7203ece8bdae0/cidc_schemas/schemas/assays/components/reads_with_index.json#L10) and then to [reads_core](https://github.com/CIMAC-CIDC/cidc-schemas/blob/a041af26493861a60f10126c0fd7203ece8bdae0/cidc_schemas/schemas/assays/components/reads_core.json#L17) which shows this is an array of files

so the correct formats would be either
```json
{
    "is_artifact": 1,
    "merge_pointer": "0/r2/0"
}
```
as you described, where `0` vs `-` are the same as it is a single item array
or
```json
{
    "is_artifact": "multi",
    "merge_pointer": "0/r2"
}
```
as in [rna eg r1](https://github.com/CIMAC-CIDC/cidc-schemas/blob/a041af26493861a60f10126c0fd7203ece8bdae0/cidc_schemas/schemas/templates/assays/rna_fastq_template.json#L43)

**Comment by crouchcd** [comment]
@scvannost Thanks for pointing to the relevant files. Will add the updates in a PR to come.
