### ISSUE TITLE
add schema linter

### ISSUE THREAD

**Issue by jim-bo** [CIMAC-CIDC/cidc-schemas#6]
HCA has schema linting, we need to do something similar.

1. Figure out what those linting standards are
2. Implement our own linting process

https://github.com/HumanCellAtlas/metadata-schema

**Comment by jacoblurye** [comment]
@jim-bo do we still intend to do this? If not, let's close this issue.

**Comment by jacoblurye** [comment]
(whoops! pressed the wrong button when I commented 😅)
