### ISSUE TITLE
Description not consistent across data model

### ISSUE THREAD

**Issue by priti88** [CIMAC-CIDC/cidc-schemas#62]
Examples in the description field is not consistent in the data model.

 "cimac_participant_id": {
      "type": "string",
      "description": "Participant identifier assigned by the CIMAC-CIDC Network. **Example: CIMAC-1234."**

 "enrichment_vendor_kit": {
      "description": "Vendor for the bait set used for enrichment, **e.g. Twist, Agilent, IDT**",
      "type": "string",
      "enum": ["Agilent - Human All Exon V7", "Twist", "IDT", "NEB"]
    },

Proposed solution: Change everything to follow the format: "Example: XYZ"

**Comment by jacoblurye** [comment]
Looking at the schemas, it seems this update has been made.
