### ISSUE TITLE
Handling boolean values in Excel files

### ISSUE THREAD

**Issue by mducar** [CIMAC-CIDC/cidc-schemas#85]
When generating the Excel files, if a data element is a boolean value the Excel file should give the user a drop down box to select True or False.    Otherwise, errors won't get caught until validation.

**Comment by mducar** [comment]
Changed this to a bug.  Typing "True" into an Excel file field results in the error:
        if invalid_messages:
            feedback = '\n'.join(invalid_messages)
>           raise ValidationError('\n' + feedback)
E           cidc_schemas.template_reader.ValidationError: 
E           RNA: Header, STRANDED LIBRARY:	4524090568 is not of type 'boolean'

cidc_schemas/template_reader.py:161: ValidationError


I've committed my branch "md299-ngs3" that you can use to reproduce the error.

**Comment by jacoblurye** [comment]
https://github.com/CIMAC-CIDC/cidc-schemas/pull/88
